### ISSUE TITLE
路径错误

### ISSUE THREAD

**Issue by makangbooo** [LooperXX/ProSLU#1]
<img width="1191" alt="image" src="https://github.com/LooperXX/ProSLU/assets/168157538/16489b95-8404-48fa-936e-14c277f73a7b">
<img width="1191" alt="image" src="https://github.com/LooperXX/ProSLU/assets/168157538/c83d3b2c-2b5c-47ad-a9e7-75c213801c44">

**Comment by LooperXX** [comment]
已修复您提供的两个文件路径名称问题，非常感谢您的贡献 🤝
